# Generated by Django 2.1.1 on 2018-09-20 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='user_msg',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_msg',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='message_comment', to='wall_app.Message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=255),
        ),
    ]
